min_quality: 20
min_depth: 10
mode: "amplicon"
samples: ["SRR37686269", "SRR37686273"]
ref_amplicon: "/rds/projects/e/elhamsak-nanothal/reference/hg38_globin.fa"
ref_wgs: "/rds/projects/e/elhamsak-nanothal/reference/hg38.fa"
clair3_path: "/rds/bear-apps/2022a/EL8-ice/software/Clair3/1.0.4-foss-2022a/bin/run_clair3.sh"
clair3_models: "models/r1041_e82_400bps_sup_v430"
sniffles_path: "/rds/homes/f/fnl759/.conda/envs/snakemake/bin/sniffles"
cutesv_path: "/rds/homes/f/fnl759/.conda/envs/snakemake/bin/cuteSV"
cutesv_min_support: 3
targets:
  HBA: "chr16:170000-178000"
  HBB: "chr11:5225000-5228000"
reference_region: "HBB"
coverage_bin_size: 200











