min_depth: 10
min_af: 0.15
mode: "amplicon"
samples: ["SRR37686269", "SRR37686273"]
ref_amplicon: "reference/hg38_globin.fa"      
ref_wgs: "reference/hg38.fa"
csq_gff: "reference/ensembl_globin.gff3.gz"
clair3_models: "models/r1041_e82_400bps_sup_v430"
cutesv_min_support: 25
targets:
  HBA: "chr16:170000-178000"
  HBB: "chr11:5225000-5228000"
reference_region: "HBB"
coverage_bin_size: 200










